name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.203'

    - name: Restore
      run: dotnet restore

    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Install mono
      run: sudo apt-get update && sudo apt-get install -y mono-devel

    - name: Run Nuke Build
      run: ./build.sh